### ISSUE TITLE
_

### ISSUE THREAD

**Issue by rideswithchrist** [SOZOGlobal/Marketing#64]
Remove Larry, correct images on Co-Founders/CEO, etc

**Comment by agrizzlyadams** [comment]
is this done?

**Comment by rideswithchrist** [comment]
This is waiting on Colin to modify the CSS to constrain the sizes of the photos. I could not dig far enough into the code to get it right. Some override was killing it.

**Comment by rideswithchrist** [comment]
but the photos are corrected.
